[package]
name = "chunk-parser"
version = "0.1.0"
authors = ["StealthOfKing <sok@monocyte.host>"]
edition = "2021"
license = "GPL-3.0"
description = "Generic chunk parser pattern"

[dependencies]
fourcc = { path = "../fourcc" }
chunk-parser-derive = { path = "../chunk-parser-derive" }
